[package]
name = "blas-rs"
version = "1.0.0-alpha.6"
edition = "2024"
authors = ["ronakgh {ronakgh97@gmail.com}"]
description = "Experimental F32 BLAS & Intel Math kernels library for x86_64 cpu"
license = "MIT"
repository = "https://github.com/ronakgh97/blas-rs"
readme = "README.md"
categories = ["mathematics", "rust-patterns", "hardware-support", "science"]
keywords = ["blas", "simd", "math", "high-performance", "x86_64"]

[lib]
name = "blas_rs"
path = "src/lib.rs"

[[bench]]
name = "bencher"
path = "bench/bencher.rs"
harness = false

[[bin]]
name = "asm_runner"
path = "asm/runner.rs"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "fat"

[dependencies]
rand = "0.10.1"
rand_xoshiro = "0.8.1" # apparently faster than my impl of splitmix64 :(
# rayon = "1.12.0" # for cpu parallel computations

[dev-dependencies]
plotters = "0.3.7" # for plotting benchmarks
blas = "0.23.0" # for BLAS bindings, used in the reference implementation and benchmarks
# externel deps, make sure to have OpenBLAS installed on your system and properly linked, or it won't compile
# check readme for instructions
openblas-src = { version = "0.10.16", features = ["system"] }