name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-C target-cpu=x86-64-v3"
  RUSTDOCFLAGS: "-C target-cpu=x86-64-v3"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenBLAS dependency
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy --all-targets --release -- -D warnings

      - name: Check
        run: cargo check --all-targets --release

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenBLAS dependency
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo nextest run --all-targets --no-fail-fast --no-capture